name: Run .py to download combined_excel.xlsx

on:
  schedule:
    
    - cron: '15 1 * * 0-5'  # Sunday (0) to Friday (5), 1:15 AM UTC (9:00 AM NPT)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Needed for pushing back to repo

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run download_all_nepse.py
        run: python download_all_nepse.py

      - name: Commit and push combined_excel.xlsx
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add combined_excel.xlsx

          # Only commit if file has changed
          git diff --cached --quiet || (
            git commit -m "Add/update combined_excel.xlsx [automated]"
            git push origin HEAD:${{ github.ref }}
          )
