name: Run .py for golden_cross from combined_excel.xlsx

on:
  workflow_run:
    workflows: ["Run .py to download combined_excel.xlsx"]
    types:
      - completed
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libjpeg-dev zlib1g-dev


      - name: Install Python dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install --upgrade pip
            pip install -r requirements.txt
          else
            echo "No requirements.txt found, skipping installation."
          fi

      - name: Run golden_cross.py
        env:
          USER_EMAIL: ${{ secrets.USER_EMAIL }}    
          USER_PASSWORD: ${{ secrets.USER_PASSWORD }}    
        run: python golden_cross.py
